init関連整理
marinebox/tab-killer pull request #105
Opened 2021-12-11 10:01 UTC by marinebox

とりあえず

2021-12-12 05:04 UTC, penicillin0 requested changes

2021-12-12 05:05 UTC, penicillin0 commented
https://github.com/marinebox/tab-killer/blob/11e197faa92c2dd077654abcd773ab8412dd7db0/src/js/whitelist.js#L148-L149

たぶんここもいらなそう

2021-12-12 05:15 UTC, penicillin0 commented on src/js/utils.js
> + * @returns {Promise<Array>} tabs object
returnsも使えるのか

2021-12-12 05:19 UTC, penicillin0 commented on src/js/utils.js
> + * @returns {Promise<Array>} tabs object
![image](https://user-images.githubusercontent.com/56141035/145701316-b2fb43a5-5bf4-4450-b7ef-124b7430090d.png)

でも`eslint`に怒られてるから`return`にしようか

2021-12-12 05:23 UTC, penicillin0 commented
@marinebox 
たぶんcommitする前に`yarn lint`とかすると`eslint`, `prettier`らへんの怒られは発見できる

まあgithub actionで自動化しろという話ではあるけど

2021-12-12 06:46 UTC, marinebox commented on src/js/utils.js
> +    return false;
本当だ。langで対応します。

(実はここの言語切り替えできない問題は今も存在する)

2021-12-12 07:31 UTC, marinebox commented on src/js/popup.js
>      .getElementById('normal_action')
これは思ってた

2021-12-12 07:35 UTC, marinebox commented on src/js/utils.js
> +  }
langで対応するつもりだったけど循環参照が良くないのか動かなくなってしまうので暫定対応

2021-12-12 07:35 UTC, marinebox commented on src/js/language.js
> +    },
ここ、次の要素が無いのに`,`入ってるの気にならない？

2021-12-12 08:45 UTC, penicillin0 commented on src/js/language.js
> +    },
これはprettierの設定で変更できるはず
Trailing Commasかな
僕はどっちでもいいから変更するなら`.prettierrc`を更新してくれい

2021-12-12 08:52 UTC, penicillin0 approved these changes
良さそう
prettierの設定は任せた

2021-12-14 12:24 UTC, penicillin0 approved these changes
![Well Done Minions](https://media.giphy.com/media/fxsqOYnIMEefC/giphy.gif)

2021-12-14 12:43 UTC, merged